### ISSUE TITLE
Release npm for major fix

### ISSUE THREAD

**Issue by mickaelvalmier** [bayorigin/uniqid#12]
Hi,

Can you bump npm version witch include major fix in pull request #11, please ?

Fail when module is web bundled (browserify).

Thanks.

**Comment by yivo** [comment]
Important for me too. Please make new release.

**Comment by adamhalasz** [comment]
Sorry for the late reply. I'll release the new version in a few hours.

**Comment by adamhalasz** [comment]
v4.1.1 has been released.

**Comment by mickaelvalmier** [comment]
No problem , thanks !
