### ISSUE TITLE
Fallback silently instead of logging to console?

### ISSUE THREAD

**Issue by ben-eb** [bayorigin/uniqid#7]
Would it be possible to silently fallback instead of logging to `stdout` when the module falls through to a less specific method? It's somewhat confusing to see this message, and as it is printed on `stdout` instead of `stderr` then it will erroneously appear in any program that utilises `stdout` for output, such as CLI applications.

Ref: https://github.com/ben-eb/gulp-cssnano/issues/51

**Comment by adamhalasz** [comment]
Hey @ben-eb sorry for the late answer! 

I see what you mean. I disabled debug messages by default in the new `v4.1.0` and they can be turned on like this:
```js
// enable debug messages
module.uniqid_debug = true

// require the module
var uniqid = require('uniqid')
```
https://github.com/bayorigin/uniqid#debug

Let me know how that works for you.

Thanks,
Adam

**Comment by ben-eb** [comment]
Thanks Adam, the patch looks good to me. Will land this update in https://github.com/postcss/postcss-filter-plugins soon. :smile:
